Repository mF2C/mF2C, pull requests merged in 2019-05, with the labels that each got.

#168 Changes to add endpoint for fetching landscaper log to landscaper web api
  docker-compose-it2/docker-compose.yml
Labels: demo

#174 Added event manager
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/tests/service-manager.sh
  docs/service_manager.md
Labels: demo

#175 Optimal optimize
  docker-compose-it2/docker-compose.yml
  docs/analytics_engine.md
Labels: demo

#177 updated hello-world and service manager tests
  docker-compose-it2/hello-world.sh
  docker-compose-it2/tests/service-manager.sh
Labels: demo

#173 dataclay fix general update CIMIResource operation field + agent update
  docker-compose-it2/docker-compose.yml
Labels: DATA MANAGEMENT, demo

#176 Solved the IP related issues
  docker-compose-it2/docker-compose.yml
  docker-compose/docker-compose.yml
Labels: demo

#179 Policies patch
  docker-compose-it2/docker-compose.yml
  docs/policies.md
Labels: RESOURCE MANAGER
