Repository mF2C/mF2C, pull requests merged in 2019-03, with the labels that each got.

#133 Update docker-compose.yml
  docker-compose-it2/docker-compose.yml
Labels: demo

#132 Update docker-compose.yml
  docker-compose-it2/docker-compose.yml
Labels: RESOURCE MANAGER, SECURITY, TESTING AND UCs, demo

#139 New agent model implemented + some improvements
  docker-compose-it2/docker-compose.yml
Labels: demo

#141 dataClay 2.9 with QoS model resource + Fixed dataClay restart bug
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/prop/global.properties
  docker-compose-it2/prop/log4j2.xml
Labels: DATA MANAGEMENT, demo

#140 Updated versions of SM and LM-UM
  docker-compose-it2/docker-compose.yml
Labels: demo

#143 Updating Landscaper & Analytics Engine Image versions
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/landscaper.cfg
Labels: demo

#144 New dataClay 2.10 with cimi-edit return fixed
  docker-compose-it2/docker-compose.yml
Labels: CIMI, DATA MANAGEMENT, demo

#146 Updating dataclay-proxy, cimi and SM versions
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/hello-world.sh
Labels: demo
