Repository mF2C/mF2C, pull requests merged in 2019-09, with the labels that each got.

#240 policies integration tests
  docker-compose/tests/policies.sh
Labels: RESOURCE MANAGER

#242 policies integration tests v2
  docker-compose/tests/policies.sh
Labels: RESOURCE MANAGER

#253 policies healthcheck
  docker-compose/docker-compose.yml
Labels: RESOURCE MANAGER

#255 Added the text for `latest-V2.0.20`
  docker-compose/docker-compose.yml
  docs/resource-categorization.md
Labels: RESOURCE MANAGER

#254 ChildrenIPs solved + install.sh modified
  docker-compose/docker-compose.yml
  docker-compose/install.sh
  docs/policies.md
Labels: RESOURCE MANAGER

#263 Production/microagent
  docker-compose-microagent/Dockerfile
  docker-compose-microagent/docker-compose.yml
  docker-compose-microagent/mf2c-entrypoint.sh
Labels: MICROAGENT

#264 New dataClay 2.24 with Healthcheck and inter-agent security ready
  docker-compose/docker-compose.yml
  docker-compose/prop/global.secure.properties
  docker-compose/traefik/traefik.toml
  docs/dcproxy.md
  docs/ds1java1.md
  docs/logicmodule1.md
Labels: DATA MANAGEMENT

#266 Exposing port until Discovery adapt to traefik ips
  docker-compose/docker-compose.yml
Labels: DATA MANAGEMENT

#268 add cimi tests
  docker-compose/tests/aclib.sh
Labels: INTERFACE, SECURITY
