Repository mF2C/mF2C, pull requests merged in 2019-04, with the labels that each got.

#147 Modified service-operation-report resource, using cimi 2.9 and dc 2.11
  docker-compose-it2/docker-compose.yml
Labels: CIMI, DATA MANAGEMENT, demo

#148 updating analytics engine image version and volume mapping in docker …
  docker-compose-it2/analytics_engine.conf
  docker-compose-it2/docker-compose.yml
Labels: demo

#149 Fix connections between intel components
  docker-compose-it2/analytics_engine.conf
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/landscaper.cfg
Labels: demo

#150 new versions of cimi, sm, sla and categorization
  docker-compose-it2/docker-compose.yml
Labels: demo

#153 Update docker-compose.yml
  docker-compose-it2/docker-compose.yml
Labels: demo

#154 dataClay 2.13 w modified Device and Device-Dynamic and new SLATemplate
  docker-compose-it2/docker-compose.yml
Labels: demo

#157 policies 2.0.0
  docker-compose-it2/docker-compose.yml
Labels: RESOURCE MANAGER, TESTING AND UCs, demo

#155 new version of SM with SLA template support
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/hello-world.sh
Labels: demo

#162 Changed the res-cat docker-image version
  docker-compose-it2/analytics_engine.conf
  docker-compose-it2/docker-compose.yml
Labels: demo

#156 Modifying landscaper.cfg and a listener to default configuration
  docker-compose-it2/landscaper.cfg
Labels: demo

#160 dataClay 2.14 with modified SLAViolation agreement id field in model
  docker-compose-it2/docker-compose.yml
Labels: BSC, DATA MANAGEMENT, demo

#161 Removing snaptemp and replacing with a smaller image (telem_start)
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/landscaper.cfg
Labels: demo

#163 updated cau-client to add shared data volume 'pkidata'.
  docker-compose-it2/docker-compose.yml
Labels: demo

#164 removed specific tag of the SM
  docker-compose-it2/docker-compose.yml
Labels: demo

#165 removed specific tag of the LM and updated hello-world test
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/hello-world.sh
Labels: demo

#166 New dataClay 2.15 with modified user-profile and sharing-model
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/tests/cimi.sh
Labels: BSC, DATA MANAGEMENT, demo

#167 Device dynamic
  docker-compose-it2/docker-compose.yml
  docker-compose-it2/landscaper.cfg
Labels: demo
