Repository mF2C/mF2C, pull requests merged in 2019-12, with the labels that each got.

#333 Fixed the storing point for the microagent's resource info
  microagent/docker-compose.yml
  microagent/mf2c-entrypoint.sh
Labels: MICROAGENT, RESOURCE MANAGER

#337 Upgrade resource-bootstrap to 2.7.3.
  agent/docker-compose.yml
  agent/docs/resource-bootstrap.md
Labels: MICROAGENT, XLAB, enhancement

#336 Modified the D-C file with new res-cat
  agent/docker-compose.yml
  agent/docs/resource-categorization.md
  microagent/docker-compose.yml
  microagent/mf2c-entrypoint.sh
Labels: bug, demo

#341 Policies 2.0.13
  agent/docker-compose.yml
  agent/docs/policies.md
Labels: RESOURCE MANAGER

#343 Upgrade resource-bootstrap to 2.7.5.
  agent/docker-compose.yml
  agent/docs/resource-bootstrap.md
Labels: XLAB

#347 Upgrade resource-bootstrap to 2.8.6.
  agent/docker-compose.yml
  agent/docs/resource-bootstrap.md
Labels: XLAB, bug

#350 Update image versions for Swarm stack support.
  agent/docker-compose.yml
Labels: CIMI, SERVICE ORCHESTRATION, XLAB, demo, enhancement

#349 Updated the res-cat with new docker images
  agent/docker-compose.yml
  agent/docs/resource-categorization.md
  microagent/mf2c-entrypoint.sh
Labels: !!!, RESOURCE MANAGER, UPC
