Repository mF2C/mF2C, pull requests merged in 2019-10, with the labels that each got.

#281 add mocking hook to lm
  docker-compose/docker-compose.yml
  docs/cimi.md
Labels: INTERFACE

#286 Stfc1
  docker-compose/docker-compose.yml
  docs/vpnclient.md
Labels: sardinia

#287 Install.sh update
  README.md
  docker-compose/install.sh
Labels: TESTING AND UCs

#293 Rm update
  docker-compose/docker-compose.yml
  docker-compose/tests/policies.sh
  docs/discovery.md
  docs/policies.md
Labels: RESOURCE MANAGER

#294 Add SlaManagementUI to docker compose
  README.md
  docker-compose/docker-compose.yml
  docs/sla_management_ui.md
Labels: SERVICE ORCHESTRATION

#279 Update docker-compose.yml and identification integration test
  docker-compose/docker-compose.yml
  docker-compose/tests/identification-FullAgent.sh
  docker-compose/tests/identification-Isolated.sh
  docker-compose/tests/identification.sh
Labels: RESOURCE MANAGER

#301 New dataClay 2.25 with service-operation-report synchronization
  docker-compose/docker-compose.yml
  docs/dcproxy.md
  docs/ds1java1.md
  docs/logicmodule1.md
Labels: DATA MANAGEMENT

#303 New dataclay 2.26 with synchronization in operation id field
  docker-compose/docker-compose.yml
  docs/dcproxy.md
  docs/ds1java1.md
  docs/logicmodule1.md
Labels: DATA MANAGEMENT

#304 New dataclay 2.27 with synchronization in service container metrics
  docker-compose/docker-compose.yml
  docs/dcproxy.md
  docs/ds1java1.md
  docs/logicmodule1.md
Labels: DATA MANAGEMENT

#306 Update resource bootstrap to v1.4.1.
  docker-compose/docker-compose.yml
Labels: Identification, USER MANAGER, XLAB

#307 Update resource-bootstrap docs up to 1.4.1.
  README.md
  docs/index.rst
  docs/resource-bootstrap.md
Labels: XLAB

#302 Policies update
  README.md
  docker-compose/docker-compose.yml
  docker-compose/install.sh
  docs/policies.md
  docs/resource-categorization.md
Labels: RESOURCE MANAGER

#311 Register cloud patch
  agent/docker-compose.yml
  agent/docs/policies.md
Labels: RESOURCE MANAGER

#312 install.sh 1.3
  agent/install.sh
Labels: TESTING AND UCs

#317 issue: bad res-cat run command
  microagent/mf2c-entrypoint.sh
Labels: MICROAGENT
